groups:

- name: node_exporter_alerts
  rules:
  - alert: Node down
    expr: up{job="Windows_Alerting"} == 0
    for: 2m
    labels:
      severity: warning
    annotations:
      title: Node {{ $labels.instance }} is down
      description: Failed to scrape {{ $labels.job }} on {{ $labels.instance }} for more than 2 minutes. Node seems down.
     
      
- name: Windows Disk Alerts
  rules:

  # Sends an alert when disk space usage is above 95%
  - alert: DiskSpaceUsage
    expr: round(100.0 - 100 * (windows_logical_disk_free_bytes / windows_logical_disk_size_bytes),0.01) > 90
    for: 10m
    labels:
      severity: high
    annotations:
      summary: "Disk Space Usage (instance {{ $labels.instance }})"
      description: "Disk Space on Drive is used more than 95%\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

  # Alerts on disks with over 85% space usage predicted to fill within the next four days
  - alert: DiskFilling
    expr: round(100 * (windows_logical_disk_free_bytes / windows_logical_disk_size_bytes) < 15 and predict_linear(windows_logical_disk_free_bytes[6h], 4 * 24 * 3600),0.01) < 0
    for: 10m
    labels:
      severity: warning
    annotations:
      summary: "Disk full in four days (instance {{ $labels.instance }})"
      description: "{{ $labels.volume }} is expected to fill up within four days. Currently {{ $value | humanize }}% is available.\n VALUE = {{ $value }}\n LABELS: {{ $labels }}"
      
- name: Windows Performance Alerts 
  rules:
  - alert: WinHostOutOfMemory
    expr: round(100 - (windows_os_physical_memory_free_bytes{job="Windows_Alerting"} / windows_cs_physical_memory_bytes{job="Windows_Alerting"}) * 100,0.1) > 50
    labels:
      severity: warning
    annotations:
      summary: "Windows Host out of memory (instance {{ $labels.instance }})"
      description: "Node memory is filling up (< 50% left)\n VALUE = {{ $value}} % \n LABELS: {{ $labels }}"

  - alert: WinHostCpuUsage
    expr: round(100 - (avg by (instance) (irate(windows_cpu_time_total{job="Windows_Alerting",mode="idle"}[2m])) * 100),0.1) > 9
    for: 5s
    labels:
      severity: warning
    annotations:
      summary: "CPU Usage more than 9% on {{$labels.instance }}"
      description: "CPU Usage is more than 9%\n CurrentUsage = {{ $value }} % \n on {{ $labels.instance }}"
      
- name: Microsoft SQL Server Alerts
  rules:

  # Sends an alert when the 'sqlserveragent' service is not in the running state for 3 minutes.
  - alert: SQL Server Agent DOWN
    expr: windows_service_state{instance="SQL",exported_name="sqlserveragent",state="running"} == 0
    for: 3m
    labels:
      severity: high
    annotations:
      summary: "Service {{ $labels.exported_name }} down"
      description: "Service {{ $labels.exported_name }} on instance {{ $labels.instance }} has been down for more than 3 minutes."

  # Sends an alert when the 'mssqlserver' service is not in the running state for 3 minutes.
  - alert: SQL Server DOWN
    expr: windows_service_state{instance="SQL",exported_name="mssqlserver",state="running"} == 0
    for: 3m
    labels:
      severity: high
    annotations:
      summary: "Service {{ $labels.exported_name }} down"
      description: "Service {{ $labels.exported_name }} on instance {{ $labels.instance }} has been down for more than 3 minutes."
      
      
- name: Monitor Automatic services
  rules:

  # Sends an alert when the Automatic Services not in the running state for 3 minutes.
  - alert: Automatic Services not running
    expr: sum by (instance,name) (windows_service_state{state!="running" ,name=~"appmgmt|gupdate|ccmsetup|perfalarmservice|universaldashboard"} == 1) + on (instance,name) sum by (instance,name) (windows_service_start_mode{start_mode="auto"} == 1)
    for: 5s
    labels:
      severity: P3
    annotations:
      summary: "Service {{ $labels.exported_name }} down"
      description: "Service {{ $labels.name }} on instance {{ $labels.instance }} has been down for more than 3 minutes." 
      
- name: Monitor Uptime more than 10 days
  rules:

  # Sends an alert when Uptime more than 10 days
  - alert: Monitor Uptime more than 10 days
    expr: round((time() - windows_system_system_up_time)/ 24 / 3600 ,0.01) > 10
    for: 5s
    labels:
      severity: warning
    annotations:
      summary: "Server {{ $labels.instance}} Uptime more than 10 days"
      description: "Server {{ $labels.instance }} has been up for more than 10 days.Uptime {{ $value }} days" 
      
- name: Monitor NetInterfaceUsage
  rules:
    - alert: NetInterfaceUsage
      expr: round(rate(windows_net_bytes_total{nic!~".*wal.*"}[2m]) / windows_net_current_bandwidth_bytes * 100,0.001) < 95
      for: 5s
      labels:
        severity: high
      annotations:
        summary: "Network Interface Usage (instance {{ $labels.instance }})"
        description: "Network traffic usage is greater than 95% for interface {{ $labels.nic }}\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"      
      
     



      
